build_from:
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
args:
  BUILD_ARCH: "{arch}"
labels:
  org.opencontainers.image.title: PresenceSync
  org.opencontainers.image.description: Track Apple Find My items in Home Assistant
  org.opencontainers.image.source: https://github.com/bexelbie/presencesync-addon
  org.opencontainers.image.licenses: MIT
